### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by ARSHADAMEEN00**

### CODE REVIEW

**Review by nediya99 — APPROVED** [review]
Readme content approved👍

**Review by ARSHADAMEEN00 — COMMENTED** [review]
the review form [nediya99](https://github.com/nediya99) is genuine and approved

**Review by Irfan-kc — APPROVED** [review]
Poli

**Review by Irfan-kc — APPROVED** [review]

**Review by Irfan-kc — APPROVED** [review]
ha

**Review by Irfan-kc — APPROVED** [review]

**Review by shibilimhd — APPROVED** [review]
Approve

**Review by Irfan-kc — COMMENTED** [review]
baa

**Review by Irfan-kc — APPROVED** [review]

**Review by nediya99 — APPROVED** [review]
Approved👍

**Pull request merged**
